name: Build DLL
on: push     
jobs:
  build_dll:
          runs-on: windows-latest
          steps:
                  - name: Checkout
                    uses: actions/checkout@v3
                    with:
                      submodules: 'recursive'
                  - name: Setup MSBuild
                    uses: microsoft/setup-msbuild@v1
                  - name: run-vcpkg
                    uses: lukka/run-vcpkg@v11
                    with:
                        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
                        vcpkgArguments: '@${{ github.workspace }}/vcpkg.txt'
                        cleanAfterBuild: false
                  - name: Check dependencies
                    run: 'ls ${{ github.workspace }}/vcpkg/installed/x86-windows-static'
                  - name: Build DLL
                    run: 'msbuild SimpleGraphic.vcxproj /p:configuration=release /p:platform=win32'
                  - name: Archive DLL
                    uses: actions/upload-artifact@v3
                    with:
                        name: SimpleGraphic.dll
                        path: '${{ github.workspace }}/Release/SimpleGraphic.dll'
