name: Build DLL
on: push     
jobs:
  build_dll:
          runs-on: windows-latest
          steps:
                  - name: Checkout
                    uses: actions/checkout@v2
                    with:
                      submodules: 'recursive'
                  - name: run-vcpkg
                    uses: lukka/run-vcpkg@v3.2
                    with:
                        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
                        vcpkgArguments: '@${{ github.workspace }}/vcpkg.txt'
                  - name: Setup MSBuild
                    uses: microsoft/setup-msbuild@v1.0.0
                  - name: Copy Dependencies
                    run: 'cp ${{ github.workspace }}/vcpkg/packages ${{ github.workspace }}/dependencies'
                  - name: Build DLL
                    run: 'msbuild SimpleGraphic.vcxproj /p:configuration=release /p:platform=win32'
                  - name: Archive DLL
                    uses: actions/upload-artifact@v1.0.0
                    with:
                        name: SimpleGraphic.dll
                        path: '${{ github.workspace }}/Release/SimpleGraphic.dll'
