name: Build DLL
on: push     
jobs:
  build_dll:
          runs-on: windows-latest
          steps:
                  - name: Checkout
                    uses: actions/checkout@v2
                  - name: run-vcpkg
                    uses: lukka/run-vcpkg@v3.2
                    with:
                        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
                        vcpkgArguments: '@${{ github.workspace }}/vcpkg.txt'
